setup.py
I've just uploaded the latest version on PyPI so that users can use the newly added algorithms. 
https://pypi.python.org/pypi?name=metric-learn&version=0.1.1&:action=display
=> Updated version on PyPI

metric_learn/__init__.py, metric_learn/covariance.py
Some papers mention using inverse of covariance matrix as a simple "metric-learning" method.
I thought it would a good idea to have this explicitly in a class.
=> Simple Covariance metric-learner

metric_learn/rca.py
Just a small typo in the docs of `rca`.
=> Fixed typo.

metric_learn/base_metric.py, metric_learn/covariance.py, metric_learn/itml.py, metric_learn/lsml.py, metric_learn/sdml.py, test/test_fit_transform.py
@perimosocordiae , could you have a look and see if this is the correct idea/direction to go in?
And this sort of `fit_transform` would be wanted for all the algorithms, correct?
This is with respect to #25.
=> [MRG] Adding fit_transform

metric_learn/base_metric.py, test/test_base_metric.py
I took the __repr__ from scikit and put it to base_metric together with _pprint.
=> Added __repr__ to BaseMetricLearner

metric_learn/itml.py
=> Clarified documentation of ITML

metric_learn/lfda.py
=> Deals with scipy's new version, where eigsh can call eigh.

metric_learn/mlkr.py, test/metric_learn_test.py
Running `scipy.check_grad` on MLKR loss function returned an error.
This PR fixes the gradient and adds a non regression test. I also modified the cost function (filling K diagonal with zeros), see comments in the code below
=> [MRG] FIX: fix MLKR cost and gradient

doc/index.rst
Add newly introduced MMC and MLKR to the documentation.
=> [MRG] Add MLKR and MMC to doc index

doc/conf.py
Update copyright field to current year (2018)
=> [MRG] Update copyright date

test/metric_learn_test.py
This PR puts back tests on NCA that were put in #99, but that I deleted unintentionnaly in PR #139
=> [MRG] FIX put back nca's tests

README.rst
=> FIX README file

metric_learn/itml.py, metric_learn/lmnn.py, metric_learn/lsml.py, metric_learn/mlkr.py, metric_learn/mmc.py, metric_learn/nca.py, metric_learn/sdml.py
=> [MRG] MAINT: remove variables not needed to store

.codecov.yml, .gitignore, .travis.yml, README.rst
Fixes #170
This PR is an intent to add the code coverage badge and PR checks to metric-learn
=> [MRG] Add test coverage

doc/conf.py
=> Add intersphinx

doc/supervised.rst, doc/unsupervised.rst, doc/user_guide.rst, doc/weakly_supervised.rst
Fixes #212 
Uniformize references
Small improvements in documentation as listed in https://github.com/metric-learn/metric-learn/pull/208#pullrequestreview-255646220
=> [WIP] Small improvements in doc

doc/introduction.rst, metric_learn/_util.py, metric_learn/base_metric.py, metric_learn/covariance.py, metric_learn/itml.py, metric_learn/lfda.py, metric_learn/lmnn.py, metric_learn/lsml.py, metric_learn/mlkr.py, metric_learn/mmc.py, metric_learn/nca.py, metric_learn/rca.py, metric_learn/sdml.py, test/metric_learn_test.py, test/test_base_metric.py, test/test_components_metric_conversion.py, test/test_mahalanobis_mixin.py, test/test_pairs_classifiers.py, test/test_quadruplets_classifiers.py
Fixes #196 
Also renamed some related methods for consistency
=> [MRG] Rename transformer_ to components_

metric_learn/lmnn.py
There was a remaining message in the Notes section of the docstring for LMNN. This PR removes it
=> [MRG] Remove message about shogun in LMNN

README.rst, doc/index.rst
This makes the README and doc index more consistent
=> [MRG] Consistent readme and doc index

README.rst, doc/index.rst
=> [MRG] Paper ref in doc

doc/weakly_supervised.rst
=> Fixed typo in tuple description.

metric_learn/lmnn.py, test.py
=> Solves #225 : adds first line to lmnn's verbose 

doc/getting_started.rst, doc/supervised.rst, metric_learn/itml.py, metric_learn/lsml.py, metric_learn/mmc.py, metric_learn/sdml.py
=> [DOC] solves several small raised issues

metric_learn/itml.py
The existing link doesn't work anymore.
=> Fix broken link to ITML paper

metric_learn/base_metric.py, test/test_pairs_classifiers.py, test/test_utils.py
=> Corrects the forgotten bits of PR #267

.travis.yml, README.rst, metric_learn/__init__.py, metric_learn/_util.py, metric_learn/base_metric.py, metric_learn/constraints.py, metric_learn/covariance.py, metric_learn/itml.py, metric_learn/lfda.py, metric_learn/lmnn.py, metric_learn/lsml.py, metric_learn/mlkr.py, metric_learn/mmc.py, metric_learn/nca.py, metric_learn/rca.py, metric_learn/sdml.py, setup.py, test/metric_learn_test.py, test/test_base_metric.py, test/test_pairs_classifiers.py
Fixes gh-166, and resolves some errors related to newer versions of scikit-learn.
=> Drop support for python 2 and python 3.5

.github/ISSUE_TEMPLATE/config.yml
This fixes 2 urls of issue buttons which were giving 404 errors
=> [MRG] Fix urls in issue buttons

metric_learn/scml.py
Match actual default value of max_iter
=> Update SCML docstring
