- metric_learn/base_metric.py
- metric_learn/itml.py
- metric_learn/lfda.py
- metric_learn/lsml.py
- metric_learn/nca.py
- metric_learn/rca.py
- metric_learn/sdml.py
I wanted to use the metric-learners in a scikit Pipeline and GridSearchCV. GridSeachCV uses get_params and set_params and so I implemented both methods on the BaseMetricLearner.
Consequently I had to move all learner parameters to dictionaries so that these two methods would get to their params.
> Added get_params, set_params and params moved to dictionary

- metric_learn/__init__.py
- metric_learn/constraints.py
- metric_learn/itml.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/rca.py
- metric_learn/sdml.py
- test/metric_learn_test.py
I needed to use the Metric Learners inside scikit Pipeline, which only calls .fit(X,y).
Therefore I renamed original .fit() to .fit_constraints(), added all of its parameters to constructor and created new .fit(), which uses the parameters from constructor to build constraints and then call .fit_constraints().
I understand this is a breaking change. If there is a better approach I want to hear it :)
This only affects methods which need special constraints: ITML, SDML, LSML, RCA
> Fit constraints

- metric_learn/lmnn.py
Attempt to fix #17 .
I have done it for LMNN, is there a need for the others?
> adds code for safe return in case of no impostors for lmnn

- metric_learn/constraints.py
- metric_learn/itml.py
- metric_learn/lsml.py
- metric_learn/rca.py
- metric_learn/sdml.py
Added options to pass a `random_seed` for all the algorithms which use it.
Addresses #33, and will help the tests for #26.
> [MRG] Added random_states

- metric_learn/__init__.py
- metric_learn/mlkr.py
- test/metric_learn_test.py
Implements MLKR (sorry I've named the branch mklr :P) algorithm mentioned in #13. @perimosocordiae could you please review once? Sorry for the loops! I'll try to make it more vectorized. I'm also checking if any mathematical mistakes have inadvertently crept in. Also, what could be a good test for this? Should it just be on the lines of `testRCA`? Sorry again for the poor quality of the code. This will surely go through many revisions.
> Added MLKR algorithm

- metric_learn/constraints.py
Removed the `random` import as we've now completely shifted to the numpy random class for any random functions.
> Removed random import

- metric_learn/itml.py
This pull request fixes a performance bug in the ITML (Information-Theoretic Metric Learning) code.
I've replaced the formula: A*(v*v)*A with (A*v)*(A*v), which improves the complexity from O(n^3) to O(n^2), as described in the original ITML paper.
note that one mathematical justification is in order, which is A=A' in all stages of the algorithm since A is a Mahalanobis matrix.
I've tested it and got the exact same numerical results, with the fraction of the time needed (hours vs. days).
> Fixes ITML performance 

- metric_learn/rca.py
- test/metric_learn_test.py
- test/test_base_metric.py
It solves the issue #49 .
The input data is projected with a PCA if the inner covariance matrix is not full rank as advised in the paper "Learning a Mahalanobis Metric from Equivalence Constraints" (JMLR 2005).
I have added two tests that do not work with the current implementation :
- A feature with a null variance
- Digits dataset
I have also tested on my own datasets, and this implementation seems robust.
> Handle rank-deficient inner covariance in RCA

- metric_learn/rca.py
The docstring mentioned a parameter `X`, although it was actually called `data` in the function definition.
> Fixed parameter name in docstring of RCA.fit()

- README.rst
- metric_learn/__init__.py
- metric_learn/_util.py
- metric_learn/itml.py
- metric_learn/mmc.py
- metric_learn/pgdm.py
- test/metric_learn_test.py
- test/test_base_metric.py
- test/test_fit_transform.py
- test/test_sklearn_compat.py
This PR implements Probabilistic Global Distance Metric Learning (PGDM) mentioned in #13, sometimes also referred to as MMC, originally proposed in the following paper:
> Eric P. Xing, Andrew Y. Ng, Michael I. Jordan and Stuart Russell
> "Distance metric learning with application to clustering with side-information."
> NIPS. Vol. 15. No. 505-512. 2002.
The implementation is mainly a translation of the [Matlab reference code](http://www.cs.cmu.edu/%7Eepxing/papers/Old_papers/code_Metric_online.tar.gz) into Python, only optimized a bit to make use of vectorization and the power of numpy. This makes this implementation 6 times faster than the reference code on the iris dataset.
Both variants of PGDM proposed in the original paper are supported: learning a full or a diagonal Mahalanobis …
> Implementation of MMC

- metric_learn/itml.py
Admittedly, the changes proposed in this PR are very small, but in my test-case with 1024-dimensional data and 90 constraints, the run-time of ITML was reduced from 27 to 12 seconds.
Besides the changes in this PR, ITML could be accelerated further by not learning the metric `A` directly, but the decomposition `L` with `A = L^T * L` instead, as suggested in the ITML paper. However, that would require an efficient function for rank-1 updates/downdates of a Cholesky decomposition which is currently not available in `scipy` or `numpy`. And I don't think you would like to make another third-party module such as [`choldate`](https://github.com/jcrudy/choldate) a dependency just because of this.
> Accelerate ITML on high-dimensional data

- README.rst
- metric_learn/base_metric.py
- metric_learn/covariance.py
- metric_learn/lsml.py
- metric_learn/sdml.py
- test/metric_learn_test.py
- test/test_transformer_metric_conversion.py
In particular, this fixes the transformers returned by ITML and LSML, improving their class-separation performance on the iris unit test:
|      |  Old  |  New  |
|------|-------|-------|
| ITML | 0.362 | 0.167 |
| LSML | 0.730 | 0.698 |
The following now holds also for all learners, including ITML, LSML, SDML and the covariance method:
learner.transformer().T.dot(learner.transformer()) == learner.metric()
This PR fixes #57.
> Define distance consistently as `(x-y)^T*M*(x-y)`

- metric_learn/lsml.py
Also:
- use `np.linalg.inv` for small matrix inverses
- clean up some minor style issues
- inline regularization loss instead of leaving it as a free function
> LSML: Don't recompute prior_inv for default args

- metric_learn/lmnn.py
**Fix mistake in LMNN**
Issue in function _find_impostors:
- the squared euclidean distance is used to compute the margins in variable "margin_radii"
- the euclidean distance is used (through the function sklearn.metrics.pairwise.pairwise_distances) to compute distances between samples of different labels in variable "dist"
- the issue is that the impostors are found by testing "dist < margin_radii" which is wrong because "dist" represent distances, and "margin_radii" represent squared distances.
I propose to solve this problem by computing always the squared distances.
**Faster LMNN** 
The use of the function sklearn.metrics.pairwise_distances gives horrible performances.
Replace it by a faster function.
Below is a little script to show the computation time of LMNN
import time
from …
> LMNN: fix mistake and improve performances

- .travis.yml
- README.rst
This PR replaces unittest by pytest. Pytest is more and more used and provides a flexible and advanced framework for testing. It is still compatible with unittests so the project testing would still work after this PR is merged. It would allow to code future tests for the new API in pytest.
> [MRG] move from unittest to pytest

- metric_learn/constraints.py
- metric_learn/itml.py
- metric_learn/lfda.py
- metric_learn/lsml.py
- metric_learn/mmc.py
- metric_learn/sdml.py
- test/metric_learn_test.py
- test/test_fit_transform.py
This PR changes the API with the first and easier case to implement of the new api (see issue https://github.com/metric-learn/metric-learn/issues/91 ): the case where there is no preprocessor but tuples are already formed and given to the algorithm as such. The main question is for algorithms that needs a covariance matrix to initialize the metric (LSML), or that compute bounds (ITML). For now I just reconstruct a dataset of points from the pairs thanks to np.unique, in order to have the same results and pass the tests, but this is probably not the best thing to do. For SDML, I could express the term involved in the loss only with formed pairs instead of datapoints, and here is a snippet that tests it: https://gist.github.com/wdevazelhes/3c349e13976613d15ebc46178c942474
Left TODO:
> [MRG + 1] Allow already formed tuples as an input.

- metric_learn/base_metric.py
- metric_learn/covariance.py
- metric_learn/itml.py
- metric_learn/lfda.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mlkr.py
- metric_learn/mmc.py
- metric_learn/nca.py
- metric_learn/rca.py
- metric_learn/sdml.py
- test/test_weakly_supervised.py
The new API should allow metric learning algorithms that fit on tuples of points to also predict, score, etc on tuples, Therefore being usable in scikit-learn's cross-validation routines. This is part of the PRs need for issue #91.
- <strike>Move docstrings from ``_fit`` to ``fit``</strike>
- <strike>Remove unused imports</strike>
> [MRG] New API should allow prediction functions and scoring

- metric_learn/nca.py
- test/metric_learn_test.py
- test/test_base_metric.py
Fixes #45 
This PR adds a more memory efficient implementation of the gradient of NCA, avoiding creation of a (n, n, d, d) matrix. This is taken from a PR I opened in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/10058
Eventually, some others improvements of this PR (like verbose, checkers, choice of initializations) would be integrated in metric-learn, but I think for now just changing the gradient computation is fine to solve #45.
Here is a little snippet to show the performance gain: 
```python
from time import time
from sklearn.datasets import load_iris, load_digits
from metric_learn import NCA
for dataset in [load_iris(), load_digits()]:
X, y = dataset.data, dataset.target
nca = NCA()
start = time()
nca.fit(X, y)
print(time() - start)
```
Prints for this PR: …
> [MRG] Add memory efficient implementation of NCA

- metric_learn/mmc.py
Fixes #74: uses addition rather than multiplication for getting the while loop started, and throw error when NaN are found
> [MRG] FIX: use addition for starting while loop and checks NaN

- metric_learn/__init__.py
- setup.py
this code should print the version number:
```python
import metric_learn
print(metric_learn.__version__)
```
However it doesn't work. 
This modification allows the version number to be accessed like this.
> [MRG] Update __init__.py to allow printing version

- metric_learn/mlkr.py
- metric_learn/nca.py
Uses [np.linalg.multi_dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.multi_dot.html) in gradient computations in `NCA` and `MLKR`. This should provide optimal performance, no matter the values of `n_components`, `n_features`, and `n_samples`.
> [MRG] Improve gradient computation in NCA and MLKR

- doc/index.rst
- doc/metric_learn.covariance.rst
- doc/metric_learn.itml.rst
- doc/metric_learn.lfda.rst
- doc/metric_learn.lmnn.rst
- doc/metric_learn.lsml.rst
- doc/metric_learn.mlkr.rst
- doc/metric_learn.mmc.rst
- doc/metric_learn.nca.rst
- doc/metric_learn.rca.rst
- doc/metric_learn.sdml.rst
- metric_learn/itml.py
- metric_learn/lsml.py
- metric_learn/mmc.py
- metric_learn/rca.py
- metric_learn/sdml.py
Fixes #22
Here is a small proposal for adding some documentation for supervised classes.
> [MRG] Add documentation for supervised classes and add __init__ docstrings to doc

- setup.py
- new algorithms
- new website
> [MRG]  FIX: Update setup.py

- setup.py
This adds the long description to setup.py to allow the README to be displayed on PyPI with the new changes in PyPI (see comment https://github.com/metric-learn/metric-learn/issues/71#issuecomment-418767379)
> [MRG] FIX: add long_description in setup.py

- setup.py
Got the following when running tests under python2.7:
```
Traceback (most recent call last):
File "setup.py", line 11, in <module>
with open('README.rst', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```
Reference: https://stackoverflow.com/questions/25049962/is-encoding-is-an-invalid-keyword-error-inevitable-in-python-2-x
> Fix python2.7 compatibility in setup.py

- metric_learn/itml.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mmc.py
- test/metric_learn_test.py
Fixes #126 #127 
This is a quick fix that fixes #126 and #127, by setting `ensure_min_samples=2` in checks of the inputs to pass scikit-learn's check_estimator test (see #127), and by updating the scores with the new values for the iris dataset.
But I opened two issues that tackle solving these problems in the long term (cf #127)
- issue #128 to decide what is the minimal number of samples that we want to allow the "fit" method on 
- issue #129 to deal with tests that test some hard values
> [MRG] Quick fix of failed tests due to new scikit-learn version (0.20.0)

- doc/index.rst
- doc/introduction.rst
- doc/supervised.rst
This PR improves the documentation by adding a proper section introducing metric learning (problem setting, mahalanobis distance, use cases and general references). A small description of the package is also added to the index page for clarity.
> [MRG] Documentation: introduction to metric learning

- metric_learn/_util.py
- metric_learn/base_metric.py
- metric_learn/covariance.py
- metric_learn/itml.py
- metric_learn/lsml.py
- metric_learn/mmc.py
- metric_learn/sdml.py
> [MRG] Move transformer_from_metric to util

- .travis.yml
- test/test_utils.py
This makes us update to the lastest pytest
> [MRG] Update pytest

- examples/plot_sandwich.py
Fixes #138 
Thanks to #162 we can now make SDML work on the sandwich example by reducing `balance_param` (see figure)
> [MRG] Fix: SDML on sandwich example

- metric_learn/_util.py
- test/test_transformer_metric_conversion.py
- test/test_utils.py
Fixes #175 
This PR fixes the problem we had with `transformer_from_metric`, by checking if the matrix is diagonal depending on the relative gap between the maximum absolute value of the outer diagonal coeffs, and the minimum absolute value of the diagonal coefficients, rather than what was done before.
It is also more robust for detecting whether to use Cholesky or the eigendecomposition: instead of computing the determinant to check if the matrix is not definite, it tries to do Cholesky and if an error is returned it does the eigendecomposition. Indeed, maybe the determinant can be not null if there is a very small eigenvalue (`v`=1e-5) (that should be considered as null), but a lot of big eigenvalues (see one example in the test)
It also raises an error message when the input is not …
> [MRG] make transformer_from_metric more robust

- metric_learn/_util.py
- test/test_utils.py
> [MRG] Add checks for labels when having pairs

- .travis.yml
- README.rst
- doc/getting_started.rst
- metric_learn/_util.py
- test/test_base_metric.py
- test/test_utils.py
Scikit-learn just released their last version 0.21, which does not support python<3.5, so I think we can update the travis script to download the 0.20.3 for python3.4 and python2.7, but still use the newest release for python3.6 (so that we test the behaviour on the new scikit-learn), what do you think ? 
Also, there were a few changes that need to be made to work with scikit-learn's new version, which this PR addresses
> [MRG] Be compatible with newer scikit-learn

- metric_learn/rca.py
- test/test_sklearn_compat.py
I noticed that we didn't test `RCA_Supervised` scikit-learn compatibility
A first problem in scikit-learn's `check_estimator` that prevented the test to pass was that `RCA_Supervised` couldn't form the default `n_chunks` number of chunks for one of the toy examples that scikit-learn had run. Fixing `num_chunks=2` ensures a normal use of the algorithm is tested (if we had put 1 chunk then it would have become a corner case)and is robuts when we cannot do a lot of chunks of data.
A second problem was just a bug when the input was int, because we couldn't substract inplace the mean to `chunk_data` (which was an array of ints, and numpy returns an error in this case).  Casting to float this object fixes it
> [MRG] Fix RCA_Supervised sklearn compat test

- metric_learn/itml.py
- test/metric_learn_test.py
Fixes #161 
This PR checks that when filling the `bounds` argument in ITML, we use any array-like of two elements
And it adds to the doc that the subsequent `bounds_` attribute will be a `numpy.ndarray`
Question: do we want to ensure that it's actually a 1D array ? For now I only check that is has size 2...
> [MRG] Add checks for bounds argument

- metric_learn/itml.py
- metric_learn/lmnn.py
- test/metric_learn_test.py
Fixes #46 
There seems to be problems in LMNN, that we might want to fix for the next release: 
(Note: to find out what to do we can also compare to https://github.com/scikit-learn/scikit-learn/pull/8602 )
-  Looking into this line the gradient seems to be of the shape of an outer product of Xs (when it should be of the shape of L) (see https://github.com/metric-learn/metric-learn/pull/193#issuecomment-489228612). (There might be a dot product with L missing:
(cf. https://github.com/scikit-learn/scikit-learn/pull/8602/files#diff2914dd42441ed8b594e69b2fe04d23f5R762)) This blocks PR #193:
https://github.com/metric-learn/metric-learn/blob/d4badc8adc0a8ce6689dd9a95e89181efaf5ee24/metric_learn/lmnn.py#L196
- Some part of the loss function seems to be an integer count, when it should be the …
> [MRG] FIX LMNN gradient and cost function

- metric_learn/covariance.py
- test/metric_learn_test.py
Fixes #204 
This PR uses the pseudo inverse in Covariance, rather than the inverse. See https://github.com/metric-learn/metric-learn/issues/204#issuecomment-492336040
> [MRG] Use pseudo-inverse in Covariance

- metric_learn/_util.py
- metric_learn/base_metric.py
- metric_learn/covariance.py
- metric_learn/itml.py
- metric_learn/lfda.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mlkr.py
- metric_learn/mmc.py
- metric_learn/nca.py
- metric_learn/rca.py
- metric_learn/sdml.py
- test/metric_learn_test.py
- test/test_base_metric.py
- test/test_fit_transform.py
- test/test_mahalanobis_mixin.py
- test/test_sklearn_compat.py
- test/test_transformer_metric_conversion.py
- test/test_utils.py
This solves #167 partially (only gives a num_dims argument to LMNN and ensures that the check is done uniformly between the algorithms)
> [MRG] Uniformize num_dims and add it for LMNN

- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mlkr.py
- metric_learn/nca.py
- metric_learn/sdml.py
- test/metric_learn_test.py
- test/test_base_metric.py
I forgot in #195 to add the changed behaviour warning for LMNN (which goes from init to auto),
This PR does it (and fixes also some typos for NCA)
> [MRG] Add ChangedBehaviorWarning message for LMNN too

- README.rst
- bench/benchmarks/iris.py
- doc/getting_started.rst
- doc/supervised.rst
- metric_learn/lmnn.py
- test/metric_learn_test.py
- test/test_base_metric.py
Fixes #132 
Fixes #192 
This removes the shogun dependency
> [MRG] Remove shogun dependency

- metric_learn/base_metric.py
- test/test_pairs_classifiers.py
- test/test_quadruplets_classifiers.py
There was a problem with scoring in LSML: this PR fixes it (and adds a non-regression test as well as a small test for prediction for pairs learners)
> [MRG] Fix quadruplets scoring

- metric_learn/base_metric.py
- test/test_sklearn_compat.py
- test/test_utils.py
I just realized there was a pb with `decision_function` for quadruplets, since it didn't work on list of lists of lists (instead of 3D arrays). It made me realize that we don't have integration test for these array-like inputs (althought we had extensive unit tests of `check_input` functions). Here is a fix. It adds a significant test time (15s, because it tests all possibilities with reasonable size datasets), but it's like other similar tests, it's hard to find smaller datasets since sometimes the algorithms do wrong on them. I've opened a separate issue (#218) for reducing the time of tests, so if everything is OK regarding everything but the time consideration, I guess we can merge
> [MRG] fix quadruplets decision_function

- metric_learn/lmnn.py
- test/metric_learn_test.py
- test/test_base_metric.py
> [MRG] Deprecate use_pca parameter of LMNN

- metric_learn/base_metric.py
- test/test_utils.py
See https://github.com/metric-learn/metric-learn/pull/232#issuecomment-508757860
> [MRG] make check_preprocessor private

- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/nca.py
- metric_learn/sdml.py
- test/test_mahalanobis_mixin.py
This sets a random state in the algorithms that didn't have it set, and tests it. See https://github.com/metric-learn/metric-learn/pull/232#issuecomment-508757860
> [MRG] Fix random state in algorithms

- .travis.yml
This will avoid wasting resources in case we are not working on a fork. PR builds will still work.
> Only build on master branch

- .travis.yml
This makes it easier to upgrade later.
> Extract skggm commit hash to an environment variable

- build_tools/travis/flake8_diff.sh
- doc/weakly_supervised.rst
- setup.py
- test/metric_learn_test.py
- test/test_components_metric_conversion.py
- test/test_mahalanobis_mixin.py
This renames all `metric-learn/metric-learn` into `scikit-learn-contrib/metric-learn`
> [MRG] Rename repo addresses

- metric_learn/constraints.py
- test/test_constraints.py
Fixes #200 
See comment https://github.com/scikit-learn-contrib/metric-learn/pull/198#issuecomment-490927459
I count for each set of instances of each label how many chunks it holds, and sum those.
If it is lower than the number of requested chunks, I raise an error.
> Break chunks generation in RCA when not enough possible chunks, fixes issue #200

- doc/conf.py
I found some info [there](https://github.com/sphinx-doc/sphinx/issues/6705) and added the workaround parameter to the `doc/conf.py` file to solve the problem. The new displaying of references requires modifying the CSS. The modification fixes issue #262
> Correct display of references problem in Sphinx 2.1.1, solves issue #262

- metric_learn/base_metric.py
- test/test_pairs_classifiers.py
The problem is due to a deprecation warning for `check_is_fitted` in the new version of sklearn (see below)
This PR fixes this by not using the attributes argument when calling `check_is_fitted`.
> Fix failing tests in last build

- metric_learn/base_metric.py
This PR reverts the changes introduced in #270. These changes were introduced to be compatible with changes in sklearn's `check_is_fitted` introduced in https://github.com/scikit-learn/scikit-learn/pull/14545
However the last release of sklearn has reverted these changes as they were creating some problems, see https://github.com/scikit-learn/scikit-learn/pull/15947
This avoids the hassle of checking Python version, and the need to have sklearn >= 0.22.0 for Python >= 3.5
> Revert changes in #270 due to revert decision in sklearn

- metric_learn/_util.py
- test/test_mahalanobis_mixin.py
- test/test_utils.py
This PR fixes #276, an issue that arises in the context of covariance initialization on an algorithm that doesn't require a PD matrix. It can happen that the calculated matrix is singular and in consequence isn't invertible, leading to non-explicative warnings. This is fixed by the use of a pseudo-inverse when a PD matrix is not required.
> Fix covariance initialization when matrix is not invertible

- metric_learn/_util.py
- metric_learn/base_metric.py
- metric_learn/constraints.py
- metric_learn/itml.py
- metric_learn/lfda.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mlkr.py
- metric_learn/mmc.py
- metric_learn/nca.py
- metric_learn/rca.py
- metric_learn/sdml.py
This PR adds some docstrings for the `Constraints` class and its `positive_negative_pairs` and `chunks` methods.
It also fixes minor docstring problems, such as missing description or default values, and indentation problems.
Combined with the doc improvements already made in #274, I think this resolves #227
> [MRG] Improve docstrings: add them for Constraints class and methods and fix minor problems

- doc/metric_learn.rst
- doc/weakly_supervised.rst
- metric_learn/base_metric.py
- metric_learn/constraints.py
- test/test_constraints.py
- test/test_triplets_classifiers.py
- test/test_utils.py
[WIP] Learning on Triplets
This PR is intended to allow the implementation of algorithms that learn on triplets by adding the base class for this kind of learner. The semantic of triplets is similar to quadruplets but the positive and negative pairs are constructed with respect to the first element of the triplet, for this the added code follows closely the one for quadruplets. 
The main reason for the creation of this is the implementation of SCML (PR  #278) an algorithm that learns on triplets. This will also enable the implementation of future algorithms that learn on triplets.
TODO:
> [MRG] Learning on Triplets

- doc/conf.py
- doc/weakly_supervised.rst
- metric_learn/_util.py
- metric_learn/base_metric.py
- metric_learn/constraints.py
- metric_learn/itml.py
- metric_learn/lfda.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mlkr.py
- metric_learn/mmc.py
- metric_learn/nca.py
- metric_learn/rca.py
- metric_learn/sdml.py
This PR corrects a few minor problems with the doc that were left out of #280 
Also added a temporary fix to a spacing issue due to a compatibility problem between `rtd_theme` and the new version of sphinx (see `conf.py` for details). This fix is used in other scikit-learn-contrib packages, such as imbalanced-learn
> [MRG] Correct a few small doc issues following #280

- .travis.yml
This fixes the CI failure due to pytest 5.x dropping support for Python 3.4
Very soon (next release?) we should ourselves drop support for Python 2.7 and 3.4, as discussed in #166
> Travis CI: correct pytest version for python 3.4

- metric_learn/mlkr.py
- metric_learn/nca.py
> Use scipy's logsumexp function

- doc/metric_learn.rst
- doc/weakly_supervised.rst
- metric_learn/__init__.py
- metric_learn/scml.py
- test/metric_learn_test.py
- test/test_base_metric.py
- test/test_mahalanobis_mixin.py
- test/test_sklearn_compat.py
- test/test_triplets_classifiers.py
- test/test_utils.py
Sparse Compositional Metric Learning (SCML) allows scalable learning of global, multi-task and multiple local Mahalanobis metrics for multi-class data under a unified framework based on sparse combinations of rank-one basis metrics. For this initial merge, only the global setting will be implemented.
The algorithm learns on triplets, so it is necessary to add the base class for the addition of this kind of algorithm. For the sake of clarity, this will be added in a separate concurrent PR.
This implementation follows closely the [matlab implementation](https://github.com/bellet/SCML) of Y. Shi, A. Bellet and F. Sha. Sparse Compositional Metric Learning. AAAI Conference on Artificial Intelligence (AAAI), 2014. [SCML paper](http://researchers.lille.inria.fr/abellet/papers/aaai14.pdf) …
> SCML : Sparse Compositional Metric Learning

- metric_learn/mmc.py
This is a quick fix to a problem that was making fail the following example for diagonal MMC:
```python
In [9]:  from sklearn.datasets import fetch_lfw_pairs 
...:  from sklearn.model_selection import cross_validate, train_test_split 
...:  from metric_learn import MMC 
...:  pairs, y_pairs = [fetch_lfw_pairs()[key] for key in ['pairs', 'target']] 
...:  pairs, _, y_pairs, _ = train_test_split(pairs, 2*y_pairs-1) 
...:  pairs = pairs.reshape(pairs.shape[0], 2, -1) 
...:  mmc = MMC(diagonal=True)
...:  mmc.fit(pairs, y_pairs)
```
what happens is that `obj_previous` (see here: https://github.com/scikit-learn-contrib/metric-learn/blob/899ef47889426cc2a6ffa606ba43b892af7b48da/metric_learn/mmc.py#L207) was such a big number (of order 10**20) that adding +1 made it stay the same number (see …
> [MRG] replace +1 by inf in MMC diag

- README.rst
- doc/index.rst
This updates the reference to the metric-learn paper in the README and the doc, following acceptance to JMLR
> Update paper ref after JMLR acceptance

- test/test_components_metric_conversion.py
- test/test_utils.py
Fixes #264 
See https://github.com/scikit-learn-contrib/metric-learn/issues/264#issuecomment-667933419
This PR fixes the test that was failing ` test_components_from_metric_edge_cases`, and at the same time tests better `_check_sdp_from_eigen`
> [MRG] Fix test for components_from_metric and add tests for _check_sdp_from_eigen

- .travis.yml
- metric_learn/sklearn_shims.py
- test/metric_learn_test.py
- test/test_base_metric.py
- test/test_components_metric_conversion.py
- test/test_mahalanobis_mixin.py
- test/test_pairs_classifiers.py
- test/test_quadruplets_classifiers.py
- test/test_sklearn_compat.py
- test/test_triplets_classifiers.py
- test/test_utils.py
Fixes #311 
- I added the workaround suggested by @bellet here: https://github.com/scikit-learn-contrib/metric-learn/issues/311#issuecomment-804229956, so that imports work both in sklearn <0.24 and >= 0.24 (EDIT: actually the old import strategy was already deprecated in 0.22, so I compared the version to 0.22)
- as well as an additional travis job to test (I chose the one with python 3.6 since it's the oldest python so I thought if someting goes wrong it might be this one, and also with skggm, since I also I'm thinking something might have more chance to go wrong when using another package... I could have put all the checks (python3.6+3.7, with/without skggm), but then I thought the travis test suite might take quite some time)
> [MRG+2] Update repo to work with both new and old scikit-learn

- .gitignore
- doc/supervised.rst
Resolves #211 
I've looked for this issue and was able to replicate the random behavior when calculating the eigenvectors. Effectively it may happen that some eigenvectors might be signed-flipped, if you execute the code at different times.
None of the scipy functions we use to calculate the eigenvectors in LFDA supports something like a 'random_state': [scipy.linalg.eigh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html), [scipy.linalg.eig ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html)and [scipy.sparse.linalg.eigsh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html)
There are two alternatives:
1. We implement some kind of "convention" to force/determine the behavior. For instance, "Every first …
> Addressing LFDA sign indeterminacy

- .github/workflows/main.yml
Resolves #325 
Developed a draft YML file that handles the migration from Travis CI to Github actions.
- Python 3.6, 3.7 and 3.8 are tested with sklearn=0.20.3 + skggm for compatibility. Python 3.9 doesn't work for some reason
- Python 3.6, 3.7, 3.8 and 3.9 are tested with latest versions of dependencies, with and without skggm
- Test reports are uploaded to Codecov, as before
- Flake8 always run in the end
- All tests run on the latest Ubuntu x64
Sorry for making too many commits, I could not find a way to debug this. But only one file is added and its automatically recognized by Guthub Actions.
This proposal is already working on my fork of metric_learning, at master branch.
> YML file: CI Migration to Github Actions

- test/metric_learn_test.py
- test/test_mahalanobis_mixin.py
- test/test_sklearn_compat.py
- test/test_triplets_classifiers.py
- test/test_utils.py
As suggested by @bellet in #339, it's better to cut SCML warnings from the root by specifying the `n_basis` value when its possible.
As all test run the iris dataset for SCML though `build_triplets` at `test_utils.py`, then we just need to scpecify `n_basis` for `SCML` and `SCML_Supervised` in the lists.
Going through the code of `SCML`, if `n_basis` is `None`, then the following default is assigned:
Default for SCML_Supervised: ([lines 579-583](https://github.com/scikit-learn-contrib/metric-learn/blob/aaf8d44b8d31d6ea418f0bd80ef86958e5081b4c/metric_learn/scml.py#L583))
```python
n_basis = min(20*n_features, n_samples*2*min(n_classes-1, n_features) - 1)
```
Default for SCML: ([line 234](https://github.com/scikit-learn-contrib/metric-learn/blob/aaf8d44b8d31d6ea418f0bd80ef86958e5081b4c/metri …
> [Tests][Warnings] Cut all warnings from SCML using a minimal solution

- metric_learn/scml.py
- test/test_triplets_classifiers.py
Related discussion https://github.com/scikit-learn-contrib/metric-learn/issues/348
cc @grudloff
> SCML: Raise ValueError if n_features larger than n_triplets

- bench/benchmarks/iris.py
- doc/supervised.rst
- doc/weakly_supervised.rst
- examples/plot_metric_learning_examples.py
- examples/plot_sandwich.py
- metric_learn/constraints.py
- metric_learn/itml.py
- metric_learn/lmnn.py
- metric_learn/lsml.py
- metric_learn/mmc.py
- metric_learn/rca.py
- metric_learn/sdml.py
- test/metric_learn_test.py
- test/test_base_metric.py
- test/test_components_metric_conversion.py
- test/test_constraints.py
- test/test_fit_transform.py
- test/test_mahalanobis_mixin.py
- test/test_sklearn_compat.py
- test/test_utils.py
Closes #257 as suggested by @bellet . Tests pass as expected.
This refactor is relevant from a user perspective.
> Rename variables, proposed by issue #257

- metric_learn/scml.py
> [MRG] Fix inaccurate SCML doctring for 'triplet_diffs' option

- doc/supervised.rst
The verbose (and almost all other parameters) need to be passed to the constructor and not the .fit() function. This was not reflected in the example snipplets for LMNN in the docs and let new users (like me) to make errors based on the docs.
> [DOC] Fixed small error in Code Snipplet in Docs

- metric_learn/sdml.py
- test/metric_learn_test.py
- test/test_base_metric.py
- test/test_pairs_classifiers.py
- test/test_utils.py
This PR fixes two problems due to updates in `pytest` and `sklearn`:
- `sklearn` has changed the name of the function implementing graphical lasso, which make SDML (and associated tests) fail when SKGGM is not installed. This PR makes a quick (and dirty?) fix that does the job - @perimosocordiae @terrytangyuan if you have a better solution let me know
- `pytest` has deprecated the syntax `pytest.warns(None)` and it raises an error since v8. I have fixed this following the guidelines provided by `pytest` (https://github.com/pytest-dev/pytest/issues/9404#issue-1076710891), which is to use `warnings.catch_warnings(record=True)` instead. This is what has been done for instance in `scipy` (https://github.com/scipy/scipy/pull/15192)
> [MRG] Fix test failures due to updated packages: deprecated pytest.warns(None) syntax + GLasso update in sklearn
